import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Niv from "./components/Niv";
import Footer from "./components/Footer";
import { Providers } from "./redux/Providers";




// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body>
        <div className="app-container">
          <Niv/>
          <main className="main-content">
            <Providers>{children}</Providers>
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
